version: '2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=b8a2012fabd783890dcd7730dba669d4
    volumes:
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: ./.
    ports:
      - 127.0.0.1:85:80
    links:
      - db

